"""link doctor and hospital profiles to users

Revision ID: 0ac9bd349b2c
Revises: <NEW_REVISION_ID>
Create Date: 2026-08-11 15:02:55.704623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac9bd349b2c'
down_revision: Union[str, Sequence[str], None] = '<NEW_REVISION_ID>'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_doctors_hospital_id'), 'doctors', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_doctors_user_id'), 'doctors', ['user_id'], unique=True)
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['id'])
    op.add_column('hospitals', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_hospitals_city'), 'hospitals', ['city'], unique=False)
    op.create_index(op.f('ix_hospitals_name'), 'hospitals', ['name'], unique=False)
    op.create_index(op.f('ix_hospitals_state'), 'hospitals', ['state'], unique=False)
    op.create_index(op.f('ix_hospitals_user_id'), 'hospitals', ['user_id'], unique=True)
    op.create_foreign_key(None, 'hospitals', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hospitals', type_='foreignkey')
    op.drop_index(op.f('ix_hospitals_user_id'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_state'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_name'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_city'), table_name='hospitals')
    op.drop_column('hospitals', 'user_id')
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_index(op.f('ix_doctors_user_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_hospital_id'), table_name='doctors')
    op.drop_column('doctors', 'user_id')
    # ### end Alembic commands ###
