"""add processing status to reports

Revision ID: 341ff4ff4405
Revises: ffb2f1315233
Create Date: 2026-08-04 02:57:15.076509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '341ff4ff4405'
down_revision: Union[str, Sequence[str], None] = 'ffb2f1315233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "reports",
    sa.Column(
        "processing_status",
        sa.String(length=20),
        nullable=False,
        server_default="processing",
    ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'processing_status')
    # ### end Alembic commands ###
